version: "3"

services:
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  order:
    build:
      context: .
      dockerfile: ./module/order/Dockerfile
    depends_on:
      - mysql
    restart: unless-stopped

  trade:
    build:
      context: .
      dockerfile: ./module/trade/Dockerfile
    depends_on:
      - mysql
    restart: unless-stopped