Server:
  RunMode: debug
  HttpPort: 80
  ReadTimeout: 60
  WriteTimeout: 60
Database:
  DBType: mysql
  Username: test
  Password: test
  Host: mysql:3306
  DBName: pokemon
  Charset: utf8
  ParseTime: True